# 系统信息配置
[server]
name = "Fastslot-API"
version = "v1.0.0"

# Flask APP
[app]

# 日志
[log]
folder = "log"
level = "debug"
format = "%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s"
prefix = "fastslot-api-log"

# 数据库
[db]
link = ""
